"""End-to-end test of lesson 5 (smart car-park gate) with deliberate mistakes."""
import asyncio, os, sys
from playwright.async_api import async_playwright
URL = 'file://' + os.path.abspath(os.path.dirname(__file__) + '/../lesson5/index.html')
OUT = os.environ.get('OUT', '/tmp/l5-test/'); os.makedirs(OUT, exist_ok=True)
BIN = lambda i: 84 + i * 112
TRASH = (1050, 560)
FAIL = []
def ok(cond, msg):
    print(('PASS ' if cond else 'FAIL ') + msg)
    if not cond: FAIL.append(msg)
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch()
        ctx = await b.new_context(viewport={'width': 1440, 'height': 900}, accept_downloads=True)
        pg = await ctx.new_page(); errs = []
        pg.on('pageerror', lambda e: errs.append('PAGEERR ' + str(e)))
        await pg.goto(URL); await pg.wait_for_timeout(2500)
        await pg.screenshot(path=OUT + '01-login.png')
        await pg.fill('#inName', '黃小華'); await pg.fill('#inCls', '2C'); await pg.fill('#inNo', '5')
        await pg.click('#loginBtn'); await pg.wait_for_timeout(500)
        await pg.click('#introDrive'); await pg.wait_for_timeout(1800)
        ok('有車' in await pg.inner_text('#introLamp'), 'intro: a car on the sensor opens the gate')
        await pg.screenshot(path=OUT + '02-intro.png', full_page=True)
        await pg.click('#introNext'); await pg.wait_for_timeout(400)
        async def c(x, y): return await pg.evaluate('''([x,y])=>{const s=document.querySelector('#hwSvg');const pt=s.createSVGPoint();pt.x=x;pt.y=y;const r=pt.matrixTransform(s.getScreenCTM());return [r.x,r.y]}''', [x, y])
        async def drag(a, bb):
            ax, ay = await c(*a); bx, by = await c(*bb)
            await pg.mouse.move(ax, ay); await pg.mouse.down()
            for i in range(1, 8): await pg.mouse.move(ax + (bx - ax) * i / 7, ay + (by - ay) * i / 7)
            await pg.mouse.up(); await pg.wait_for_timeout(120)
        P = await pg.evaluate('()=>{const o={};for(const k in HW.P) o[k]=[HW.P[k].x,HW.P[k].y];return o}')
        H = lambda k, dx=0, dy=0: (P[k][0] + dx, P[k][1] + dy)
        async def check(n, label=''):
            await pg.click(f'[data-check="{n}"]'); await pg.wait_for_timeout(150)
            t = (await pg.inner_text('#hwIssues')).replace('\n', ' ')
            print(f'   step {n} {label}:', t[:140]); return t
        async def wire(a, bb, color=None):
            if color is not None: await pg.click(f'#swatches .sw:nth-child({color})')
            await drag(H(a), H(bb))
        await drag((BIN(0), 575), H('f7', 10, -23)); await drag((BIN(1), 574), H('h3', 40))
        ok('正確' in await check(1), 'step 1 sensor + 10kΩ')
        await wire('P:5V', 'tp1', 3); await wire('P:GND', 'tn1', 1)
        ok('正確' in await check(2), 'step 2 rails')
        await wire('j3', 'tp3', 3); await wire('j8', 'tn8', 1); await wire('P:A0', 'j7', 4)
        ok('正確' in await check(3), 'step 3 sensor circuit')
        await drag((BIN(2), 575), H('f13', 10, -23)); await drag((BIN(3), 575), H('f19', 10, -23))
        await drag((BIN(4), 574), H('h9', 40)); await drag((BIN(4), 574), H('h15', 40))
        ok('正確' in await check(4), 'step 4 LEDs and 220Ω')
        await wire('P:D10', 'j9', 5); await wire('P:D12', 'j15', 3); await wire('j14', 'tn14', 1); await wire('j20', 'tn20', 1)
        t = await check(5, 'swapped')
        ok('D10' in t and '已記錄 1 次' in t, 'step 5: red / green pins swapped is an error')
        await drag(H('P:D10'), TRASH); await drag(H('P:D12'), TRASH)
        await wire('P:D12', 'j9', 3); await wire('P:D10', 'j15', 5)
        ok('正確' in await check(5), 'step 5 fixed')
        await wire('P:SVG', 'tp2', 1); await wire('P:SV5', 'tn2', 3)
        t = await check(6, 'servo power reversed')
        ok('接反' in t, 'step 6: servo brown / red reversed is an error')
        await pg.screenshot(path=OUT + '03-servo-error.png')
        await drag(H('P:SVG'), TRASH); await drag(H('P:SV5'), TRASH)
        await wire('P:SVG', 'tn2', 1); await wire('P:SV5', 'tp2', 3)
        ok('正確' in await check(6), 'step 6 fixed')
        await wire('P:SVS', 'P:D9', 2)
        ok('正確' in await check(7), 'step 7 orange to D9')
        await check(8)
        hw = await pg.evaluate('()=>({e:S.hw.errors,h:S.hw.hints,done:S.hw.done})')
        ok(hw['done'] and hw['e'] == 2, f'wiring done with 2 errors {hw}')
        await pg.screenshot(path=OUT + '04-hw-done.png')
        await pg.click('.modal .actions .btn.go'); await pg.wait_for_timeout(300)
        # ---- code ----
        vals = {'b1': 'servo.h', 'b2': '720', 'b3': 'attach', 'b4': '9', 'b5': 'write', 'b6': '180', 'b7': '3', 'b8': '0'}
        for k, v in vals.items(): await pg.fill('#blank-' + k, v)
        await pg.click('[data-menu="tools"]'); await pg.hover('.menu .mi:has-text("Board")'); await pg.hover('.menu .mi:has-text("Arduino AVR Boards")')
        await pg.click('.menu .mi span:text-is("Arduino Uno")'); await pg.wait_for_timeout(100)
        await pg.click('#btnVerify'); await pg.wait_for_timeout(1700)
        out = await pg.inner_text('#ideOut'); print(out[:400])
        ok('Parking_Gate.ino:3:10: fatal error: servo.h: No such file or directory' in out and 'compilation terminated.' in out, 'compile: wrong #include is a fatal error')
        await pg.fill('#blank-b1', 'Servo.h'); await pg.fill('#blank-b3', 'Attach')
        await pg.click('#btnVerify'); await pg.wait_for_timeout(1700)
        out = await pg.inner_text('#ideOut')
        ok("'class Servo' has no member named 'Attach'; did you mean 'attach'?" in out, 'compile: Servo member error')
        await pg.screenshot(path=OUT + '05-compile.png')
        await pg.fill('#blank-b3', 'attach')
        await pg.click('#btnCheck'); await pg.wait_for_timeout(200)
        lst = await pg.inner_text('#codePanel .blist')
        ok('轉過頭' in lst and '毫秒' in lst, 'feedback: 180° and seconds')
        await pg.fill('#blank-b6', '90'); await pg.fill('#blank-b7', '3000')
        await pg.click('#btnCheck'); await pg.wait_for_timeout(200); await pg.click('.modal .actions .btn.go')
        ok(await pg.evaluate('()=>S.code.done'), 'all blanks correct')
        await pg.click('#btnUsb'); await pg.click('[data-menu="tools"]'); await pg.hover('.menu .mi:has-text("Port")'); await pg.click('.menu .mi:has-text("(Arduino Uno)")')
        await pg.click('#btnUpload'); await pg.wait_for_timeout(4300)
        ok(await pg.is_visible('.gate-big'), 'result shows the car park')
        glow = lambda col: pg.evaluate(f"()=>+document.querySelector('.modal [data-led=\"{col}\"] .ledglow').getAttribute('opacity')")
        ok(await glow('red') == 1 and await glow('green') == 0, 'no car: red on')
        await pg.click('.modal .np-drive'); await pg.wait_for_timeout(1800)
        ang = int(await pg.inner_text('.np-ang'))
        ok(await glow('green') == 1 and ang >= 85, f'car on sensor: green on, gate up ({ang}°)')
        horn = await pg.evaluate("()=>document.querySelector('.modal .svhorn').getAttribute('transform')")
        ok('rotate(-9' in horn, f'servo horn turns in the circuit ({horn})')
        await pg.screenshot(path=OUT + '06-gate-open.png')
        await pg.wait_for_timeout(4500)
        ok(int(await pg.inner_text('.np-ang')) <= 2 and await glow('red') == 1, 'after 3 s the gate closes and red is back')
        mon = (await pg.inner_text('.smon-out')).strip().splitlines()
        ok(mon and mon[-1].isdigit(), f'serial monitor shows readings ({mon[-1] if mon else ""})')
        await pg.click('.modal .actions .btn.go'); await pg.wait_for_timeout(400)
        ok('int threshold = 720;' in await pg.input_value('#codeText'), "full program uses the student's threshold")
        await pg.fill('[data-rd="room"]', '450'); await pg.fill('[data-rd="dark"]', '990')
        ok('720' in await pg.inner_text('#rdAdvice'), 'reading advice suggests the midpoint')
        await pg.screenshot(path=OUT + '07-real.png', full_page=True)
        await pg.click('#toReport'); await pg.click('.modal .actions .btn.go'); await pg.wait_for_timeout(500)
        rec = await pg.evaluate('()=>buildRecord()')
        ok(rec['score']['hw'] == 32 and rec['score']['up'] == 20 and rec['code']['blanks'][1]['ans'] == '720', f"scores {rec['score']}")
        await pg.screenshot(path=OUT + '08-report.png', full_page=True)
        async with pg.expect_download() as dl: await pg.click('#dlReport')
        d = await dl.value; path = OUT + 'report.html'; await d.save_as(path)
        ok(d.suggested_filename.startswith('停車場閘門_2C_5'), 'file ' + d.suggested_filename)
        rp = await ctx.new_page(); await rp.goto('file://' + path); await rp.wait_for_timeout(300)
        rt = await rp.inner_text('#r')
        ok('驗證碼有效' in rt and '智能停車場閘門' in rt and '990' in rt, 'report file valid')
        await pg.click('#teacherBtn'); await pg.fill('#pwIn', 'dt2026'); await pg.click('.modal .btn.primary'); await pg.wait_for_timeout(200)
        await pg.click('#tpVerify'); await pg.set_input_files('#vFile', [path, '/tmp/l4-test/report.html'] if os.path.exists('/tmp/l4-test/report.html') else [path]); await pg.wait_for_timeout(400)
        vt = await pg.inner_text('#vTbl'); print(vt)
        ok('有效' in vt, 'verifier accepts the lesson 5 report')
        if os.path.exists('/tmp/l4-test/report.html'): ok('無效' in vt, 'verifier rejects a lesson 4 report')
        async with pg.expect_download() as dl2: await pg.click('#vCsv')
        d2 = await dl2.value; await d2.save_as(OUT + 'out.csv'); csv = open(OUT + 'out.csv', encoding='utf-8-sig').read()
        ok('延伸1管理員按鈕' in csv, 'CSV headers')
        errs = [e for e in errs if 'ERR_TUNNEL' not in e]
        ok(not errs, f'no page errors {errs}')
        await b.close()
    print('FAILURES:', FAIL)
    sys.exit(1 if FAIL else 0)
asyncio.run(main())
