import asyncio, json, re, sys
from playwright.async_api import async_playwright
import os
URL='file://'+os.path.abspath(os.path.dirname(__file__)+'/../lesson2/index.html')
OUT=os.environ.get('OUT','/tmp/sos-test/'); os.makedirs(OUT,exist_ok=True)
async def main():
    async with async_playwright() as p:
        b=await p.chromium.launch()
        ctx=await b.new_context(viewport={'width':1440,'height':900}, accept_downloads=True)
        pg=await ctx.new_page()
        errs=[]
        pg.on('pageerror', lambda e: errs.append('PAGEERR '+str(e)))
        pg.on('console', lambda m: errs.append('CONSOLE '+m.text) if m.type=='error' else None)
        await pg.goto(URL); await pg.wait_for_timeout(500)
        await pg.screenshot(path=OUT+'01-login.png')
        await pg.fill('#inName','陳大文'); await pg.fill('#inCls','2a'); await pg.fill('#inNo','12')
        await pg.click('#loginBtn'); await pg.wait_for_timeout(600)
        await pg.screenshot(path=OUT+'02-intro.png', full_page=True)
        await pg.click('#introNext'); await pg.wait_for_timeout(400)
        async def c(x,y):
            return await pg.evaluate('''([x,y])=>{const s=document.querySelector('#hwSvg');const pt=s.createSVGPoint();pt.x=x;pt.y=y;const r=pt.matrixTransform(s.getScreenCTM());return [r.x,r.y]}''',[x,y])
        async def drag(a,b):
            ax,ay=await c(*a); bx,by=await c(*b)
            await pg.mouse.move(ax,ay); await pg.mouse.down()
            for i in range(1,8):
                await pg.mouse.move(ax+(bx-ax)*i/7, ay+(by-ay)*i/7)
            await pg.mouse.up(); await pg.wait_for_timeout(150)
        P=await pg.evaluate('()=>{const o={};for(const k of ["f13","f14","h9","h13","j9","j14","j13","P:D13","P:GND","P:5V"]) o[k]=[HW.P[k].x,HW.P[k].y];return o}')
        # LED: grab at body (105, 575) ; leg1 tray (95,596) -> offset (10,-21)
        await drag((105,575),(P['f13'][0]+10,P['f13'][1]-21))
        await pg.click('[data-check="1"]'); await pg.wait_for_timeout(200)
        print('after step1', await pg.inner_text('#hwIssues'))
        # resistor grab at body (246,578); leg1 (206,578) offset (40,0)
        await drag((246,578),(P['h9'][0]+40,P['h9'][1]))
        await pg.click('[data-check="2"]'); await pg.wait_for_timeout(200)
        print('after step2', await pg.inner_text('#hwIssues'))
        # wrong: D13 to a14 (cathode column)
        await drag(tuple(P['P:D13']),tuple(P['j14']))
        await pg.click('[data-check="3"]'); await pg.wait_for_timeout(200)
        print('reversed?', await pg.inner_text('#hwIssues'))
        await pg.screenshot(path=OUT+'03-hw-error.png')
        # move wire end from a14 to a9
        await drag(tuple(P['j14']),tuple(P['j9']))
        await pg.click('[data-check="3"]'); await pg.wait_for_timeout(200)
        print('step3', await pg.inner_text('#hwIssues'))
        # choose black and wire GND
        await pg.click('#swatches .sw:nth-child(4)')
        await drag(tuple(P['P:GND']),tuple(P['j14']))
        await pg.click('[data-check="4"]'); await pg.wait_for_timeout(200)
        await pg.click('[data-check="5"]'); await pg.wait_for_timeout(400)
        await pg.screenshot(path=OUT+'04-hw-done.png')
        print('hw state', await pg.evaluate('()=>({e:S.hw.errors,h:S.hw.hints,done:S.hw.done,log:S.hw.log.map(l=>l.msg)})'))
        await pg.click('.modal .btn.go'); await pg.wait_for_timeout(400)
        # code
        vals={'b1':'13','b2':'output','b3':'HIGH','b4':'0.2','b5':'LOW','b6':'600','b7':'digitalwrite','b8':'2000'}
        for k,v in vals.items(): await pg.fill('#blank-'+k, v)
        await pg.click('#btnVerify'); await pg.wait_for_timeout(900)
        print('verify no board:', await pg.inner_text('#ideOut'))
        await pg.click('#btnCheck'); await pg.wait_for_timeout(300)
        await pg.screenshot(path=OUT+'05-code-wrong.png')
        # tools > board > AVR > Uno ; then verify to see compile errors
        await pg.click('[data-menu="tools"]'); await pg.wait_for_timeout(100)
        await pg.hover('.menu .mi:has-text("Board")'); await pg.wait_for_timeout(100)
        await pg.hover('.menu .mi:has-text("Arduino AVR Boards")'); await pg.wait_for_timeout(100)
        await pg.screenshot(path=OUT+'06-menu.png')
        await pg.click('.menu .mi span:text-is("Arduino Mega or Mega 2560")'); await pg.wait_for_timeout(100)
        await pg.click('#btnVerify'); await pg.wait_for_timeout(1700)
        print('compile errs:', await pg.inner_text('#ideOut'))
        print('explain:', await pg.inner_text('#codeExplain'))
        await pg.screenshot(path=OUT+'07-compile-err.png')
        for k,v in {'b2':'OUTPUT','b4':'200','b7':'digitalWrite'}.items(): await pg.fill('#blank-'+k, v)
        await pg.click('#btnCheck'); await pg.wait_for_timeout(300)
        await pg.click('.modal .btn.go'); await pg.wait_for_timeout(200)
        # upload with no port
        await pg.click('#btnUpload'); await pg.wait_for_timeout(1800)
        print('no port:', await pg.inner_text('#ideOut'))
        await pg.click('#btnUsb'); await pg.wait_for_timeout(200)
        await pg.click('[data-menu="tools"]'); await pg.hover('.menu .mi:has-text("Port")'); await pg.wait_for_timeout(100)
        await pg.click('.menu .mi:has-text("(Arduino Uno)")'); await pg.wait_for_timeout(100)
        await pg.click('#btnUpload'); await pg.wait_for_timeout(2600)
        print('wrong board:', (await pg.inner_text('#ideOut'))[-200:])
        await pg.click('#boardSelBtn'); await pg.click('.menu .mi:has-text("Arduino Uno")'); await pg.wait_for_timeout(100)
        await pg.click('#btnVerify'); await pg.wait_for_timeout(3200)
        await pg.click('#btnUpload'); await pg.wait_for_timeout(4200)
        await pg.screenshot(path=OUT+'08-upload-ok.png')
        print('up state', await pg.evaluate('()=>S.up'))
        await pg.click('.modal .btn.go'); await pg.wait_for_timeout(400)
        await pg.screenshot(path=OUT+'09-real.png', full_page=True)
        await pg.click('#toReport'); await pg.wait_for_timeout(200)
        await pg.click('.modal .btn.go'); await pg.wait_for_timeout(500)
        await pg.screenshot(path=OUT+'10-report.png', full_page=True)
        async with pg.expect_download() as dl:
            await pg.click('#dlReport')
        d=await dl.value
        path=OUT+'report.html'; await d.save_as(path)
        print('download name', d.suggested_filename)
        # open report
        rp=await ctx.new_page(); rp.on('pageerror', lambda e: errs.append('REPORTERR '+str(e)))
        await rp.goto('file://'+path); await rp.wait_for_timeout(400)
        print('report verify:', await rp.inner_text('.rver'))
        await rp.screenshot(path=OUT+'11-reportfile.png', full_page=True)
        txt=open(path,encoding='utf-8').read()
        tam=txt.replace('\\"total\\":','\\"total\\":1',1) if '\\"total\\":' in txt else None
        print('tamper possible', tam is not None)
        open(OUT+'tampered.html','w',encoding='utf-8').write(tam)
        await rp.goto('file://'+OUT+'tampered.html'); await rp.wait_for_timeout(300)
        print('tampered verify:', await rp.inner_text('.rver'))
        # verifier
        await pg.click('#teacherBtn'); await pg.fill('#pwIn','dt2026'); await pg.click('.modal .btn.primary'); await pg.wait_for_timeout(200)
        await pg.click('#tpVerify'); await pg.wait_for_timeout(200)
        await pg.set_input_files('#vFile',[path, OUT+'tampered.html']); await pg.wait_for_timeout(500)
        print('verifier:', await pg.inner_text('#vTbl'))
        await pg.screenshot(path=OUT+'12-verifier.png')
        async with pg.expect_download() as dl2:
            await pg.click('#vCsv')
        d2=await dl2.value; await d2.save_as(OUT+'out.csv')
        print(open(OUT+'out.csv',encoding='utf-8-sig').read())
        print('ERRORS:', errs)
        await b.close()
asyncio.run(main())
