"""End-to-end test of lesson 3 (pedestrian crossing) with deliberate mistakes."""
import asyncio, os
from playwright.async_api import async_playwright
URL = 'file://' + os.path.abspath(os.path.dirname(__file__) + '/../lesson3/index.html')
OUT = os.environ.get('OUT', '/tmp/l3-test/'); os.makedirs(OUT, exist_ok=True)
BIN = lambda i: 84 + i * 112
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch()
        ctx = await b.new_context(viewport={'width': 1440, 'height': 900}, accept_downloads=True)
        pg = await ctx.new_page(); errs = []
        pg.on('pageerror', lambda e: errs.append('PAGEERR ' + str(e)))
        await pg.goto(URL); await pg.wait_for_timeout(1200)
        await pg.screenshot(path=OUT + '01-login.png')
        await pg.fill('#inName', '黃小華'); await pg.fill('#inCls', '2C'); await pg.fill('#inNo', '5')
        await pg.click('#loginBtn'); await pg.wait_for_timeout(1500)
        await pg.screenshot(path=OUT + '02-intro.png', full_page=True)
        await pg.click('#introNext'); await pg.wait_for_timeout(400)
        async def c(x, y): return await pg.evaluate('''([x,y])=>{const s=document.querySelector('#hwSvg');const pt=s.createSVGPoint();pt.x=x;pt.y=y;const r=pt.matrixTransform(s.getScreenCTM());return [r.x,r.y]}''', [x, y])
        async def drag(a, bb):
            ax, ay = await c(*a); bx, by = await c(*bb)
            await pg.mouse.move(ax, ay); await pg.mouse.down()
            for i in range(1, 8): await pg.mouse.move(ax + (bx - ax) * i / 7, ay + (by - ay) * i / 7)
            await pg.mouse.up(); await pg.wait_for_timeout(120)
        P = await pg.evaluate('()=>{const o={};for(const k in HW.P) o[k]=[HW.P[k].x,HW.P[k].y];return o}')
        H = lambda k, dx=0, dy=0: (P[k][0] + dx, P[k][1] + dy)
        async def check(n, label=''):
            await pg.click(f'[data-check="{n}"]'); await pg.wait_for_timeout(150)
            t = (await pg.inner_text('#hwIssues')).replace('\n', ' ')
            print(f'step {n} {label}:', t[:150]); return t
        async def wire(a, bb, color=None):
            if color is not None: await pg.click(f'#swatches .sw:nth-child({color})')
            await drag(H(a), H(bb))
        # 1 LEDs
        for i, hole in enumerate(['f5', 'f11', 'f17']):
            await drag((BIN(i), 575), H(hole, 10, -23))
        await check(1)
        # 2 resistors: 10k on green by mistake
        await drag((BIN(3), 574), H('h1', 40)); await drag((BIN(3), 574), H('h7', 40)); await drag((BIN(4), 574), H('h13', 40))
        await check(2, 'wrong resistor')
        await pg.screenshot(path=OUT + '03-res-error.png')
        await drag(H('h13', 40), (991, 560))
        await drag((BIN(3), 574), H('h13', 40))
        await check(2)
        # 3 signals
        await wire('P:D12', 'j1', 3); await wire('P:D11', 'j7', 2); await wire('P:D10', 'j13', 5)
        await check(3)
        # 4 GND via rail, forget green
        await wire('P:GND', 'tn1', 1); await wire('j6', 'tn6'); await wire('j12', 'tn12')
        await check(4, 'forgot green')
        await wire('j18', 'tn18')
        await check(4)
        # 5 button (tray orientation is wrong)
        await drag((BIN(5), 568), H('f19', 20, 20))
        await check(5, 'rotated')
        await pg.screenshot(path=OUT + '04-btn-rot.png')
        cx, cy = await c(*H('f19', 20, 20)); await pg.mouse.click(cx, cy); await pg.wait_for_timeout(100)
        await pg.click('#stRot'); await pg.wait_for_timeout(100)
        await check(5)
        # 6
        await wire('P:5V', 'j19', 3); await wire('P:D2', 'j21', 4)
        await check(6)
        # 7 pull-down
        await drag((BIN(4), 574), H('h21', 40))
        await check(7, 'no gnd yet')
        await wire('j25', 'tn25', 1)
        await check(7); await check(8)
        await pg.screenshot(path=OUT + '05-hw-done.png')
        print('hw', await pg.evaluate('()=>({e:S.hw.errors,h:S.hw.hints,done:S.hw.done})'))
        await pg.click('.modal .btn.go'); await pg.wait_for_timeout(300)
        # code
        for k, v in {'b1': '10', 'b2': '2', 'b3': 'input', 'b4': 'digitalRead', 'b5': '=', 'b6': 'HIGH', 'b7': '5', 'b8': 'greenPin'}.items():
            await pg.fill('#blank-' + k, v)
        await pg.click('[data-menu="tools"]'); await pg.hover('.menu .mi:has-text("Board")'); await pg.hover('.menu .mi:has-text("Arduino AVR Boards")')
        await pg.click('.menu .mi span:text-is("Arduino Uno")'); await pg.wait_for_timeout(100)
        await pg.click('#btnVerify'); await pg.wait_for_timeout(1700)
        print('compile:', (await pg.inner_text('#ideOut'))[:700])
        await pg.click('#btnCheck'); await pg.wait_for_timeout(200)
        print('check:', (await pg.inner_text('#codePanel .blist')).replace('\n', ' | ')[:600])
        await pg.screenshot(path=OUT + '06-code-err.png')
        for k, v in {'b3': 'INPUT', 'b5': '==', 'b7': '5000', 'b8': 'yellowPin'}.items(): await pg.fill('#blank-' + k, v)
        await pg.click('#btnCheck'); await pg.wait_for_timeout(200); await pg.click('.modal .btn.go')
        await pg.click('#btnUpload'); await pg.wait_for_timeout(1900)
        print('no port:', (await pg.inner_text('#codeExplain'))[:80])
        await pg.click('#btnUsb'); await pg.click('[data-menu="tools"]'); await pg.hover('.menu .mi:has-text("Port")'); await pg.click('.menu .mi:has-text("(Arduino Uno)")')
        await pg.click('#btnUpload'); await pg.wait_for_timeout(4300)
        await pg.click('#resPress'); await pg.wait_for_timeout(800)
        await pg.screenshot(path=OUT + '07-result-yellow.png')
        await pg.wait_for_timeout(2500)
        print('phase:', await pg.inner_text('#resPhase'))
        await pg.screenshot(path=OUT + '08-result-red.png')
        await pg.click('.modal .actions .btn.go'); await pg.wait_for_timeout(400)
        await pg.screenshot(path=OUT + '09-real.png', full_page=True)
        await pg.click('#toReport'); await pg.click('.modal .actions .btn.go'); await pg.wait_for_timeout(500)
        await pg.screenshot(path=OUT + '10-report.png', full_page=True)
        async with pg.expect_download() as dl: await pg.click('#dlReport')
        d = await dl.value; path = OUT + 'report.html'; await d.save_as(path); print('file', d.suggested_filename)
        rp = await ctx.new_page(); await rp.goto('file://' + path); await rp.wait_for_timeout(300)
        print('report verify:', (await rp.inner_text('.rver')).replace('\n', ' '))
        txt = open(path, encoding='utf-8').read().replace('\\"total\\":', '\\"total\\":1', 1)
        open(OUT + 'tampered.html', 'w', encoding='utf-8').write(txt)
        await rp.goto('file://' + OUT + 'tampered.html'); await rp.wait_for_timeout(300)
        print('tampered:', (await rp.inner_text('.rver')).replace('\n', ' '))
        await pg.click('#teacherBtn'); await pg.fill('#pwIn', 'dt2026'); await pg.click('.modal .btn.primary'); await pg.wait_for_timeout(200)
        await pg.click('#tpVerify'); await pg.set_input_files('#vFile', [path, OUT + 'tampered.html']); await pg.wait_for_timeout(400)
        print('verifier:', await pg.inner_text('#vTbl'))
        async with pg.expect_download() as dl2: await pg.click('#vCsv')
        d2 = await dl2.value; await d2.save_as(OUT + 'out.csv'); print(open(OUT + 'out.csv', encoding='utf-8-sig').read())
        print('ERRORS:', errs)
        await b.close()
asyncio.run(main())
