"""End-to-end test of lesson 4 (automatic night light) with deliberate mistakes."""
import asyncio, os, sys
from playwright.async_api import async_playwright
URL = 'file://' + os.path.abspath(os.path.dirname(__file__) + '/../lesson4/index.html')
OUT = os.environ.get('OUT', '/tmp/l4-test/'); os.makedirs(OUT, exist_ok=True)
BIN = lambda i: 84 + i * 112
TRASH = (1050, 560)
FAIL = []
def ok(cond, msg):
    print(('PASS ' if cond else 'FAIL ') + msg)
    if not cond: FAIL.append(msg)
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch()
        ctx = await b.new_context(viewport={'width': 1440, 'height': 900}, accept_downloads=True)
        pg = await ctx.new_page(); errs = []
        pg.on('pageerror', lambda e: errs.append('PAGEERR ' + str(e)))
        await pg.goto(URL); await pg.wait_for_timeout(1200)
        await pg.screenshot(path=OUT + '01-login.png')
        await pg.fill('#inName', '黃小華'); await pg.fill('#inCls', '2C'); await pg.fill('#inNo', '5')
        await pg.click('#loginBtn'); await pg.wait_for_timeout(800)
        await pg.fill('#introSlider', '100'); await pg.wait_for_timeout(500)
        ok('開燈' in await pg.inner_text('#introLamp'), 'intro: covered sensor turns the lamp on')
        await pg.screenshot(path=OUT + '02-intro.png', full_page=True)
        await pg.click('#introNext'); await pg.wait_for_timeout(400)
        async def c(x, y): return await pg.evaluate('''([x,y])=>{const s=document.querySelector('#hwSvg');const pt=s.createSVGPoint();pt.x=x;pt.y=y;const r=pt.matrixTransform(s.getScreenCTM());return [r.x,r.y]}''', [x, y])
        async def drag(a, bb):
            ax, ay = await c(*a); bx, by = await c(*bb)
            await pg.mouse.move(ax, ay); await pg.mouse.down()
            for i in range(1, 8): await pg.mouse.move(ax + (bx - ax) * i / 7, ay + (by - ay) * i / 7)
            await pg.mouse.up(); await pg.wait_for_timeout(120)
        P = await pg.evaluate('()=>{const o={};for(const k in HW.P) o[k]=[HW.P[k].x,HW.P[k].y];return o}')
        H = lambda k, dx=0, dy=0: (P[k][0] + dx, P[k][1] + dy)
        async def check(n, label=''):
            await pg.click(f'[data-check="{n}"]'); await pg.wait_for_timeout(150)
            t = (await pg.inner_text('#hwIssues')).replace('\n', ' ')
            print(f'   step {n} {label}:', t[:140]); return t
        async def wire(a, bb, color=None):
            if color is not None: await pg.click(f'#swatches .sw:nth-child({color})')
            await drag(H(a), H(bb))
        # 1 light sensor
        await drag((BIN(0), 575), H('f7', 10, -23))
        ok('正確' in await check(1), 'step 1 sensor placed')
        # 2 wrong resistor (220) first
        await drag((BIN(3), 574), H('h3', 40))
        t = await check(2, 'wrong resistor')
        ok('10kΩ' in t and '已記錄 1 次' in t, 'step 2: 220Ω on the sensor is an error')
        await pg.screenshot(path=OUT + '03-res-error.png')
        await drag(H('h3', 40), TRASH)
        await drag((BIN(1), 574), H('h3', 40))
        ok('正確' in await check(2), 'step 2 fixed with 10kΩ')
        # 3 rails
        await wire('P:5V', 'tp1', 3); await wire('P:GND', 'tn1', 1)
        ok('正確' in await check(3), 'step 3 rails')
        # 4
        await wire('j3', 'tp3', 3); await wire('j8', 'tn8', 1)
        ok('正確' in await check(4), 'step 4 pull-up to + rail, sensor to − rail')
        # 5 A1 by mistake
        await wire('P:A1', 'j7', 4)
        t = await check(5, 'A1')
        ok('A0' in t and '已記錄' in t, 'step 5: A1 instead of A0 is an error')
        await drag(H('P:A1'), TRASH)
        await wire('P:A0', 'j7', 4)
        ok('正確' in await check(5), 'step 5 A0')
        # 6 LED + 220
        await drag((BIN(2), 575), H('f15', 10, -23)); await drag((BIN(3), 574), H('h11', 40))
        ok('正確' in await check(6), 'step 6 LED and 220Ω')
        # 7: forget LED GND first
        await wire('P:D9', 'j11', 5)
        t = await check(7, 'no LED gnd')
        ok('GND' in t, 'step 7 reminds LED GND')
        await wire('j16', 'tn16', 1)
        await check(7); await check(8)
        hw = await pg.evaluate('()=>({e:S.hw.errors,h:S.hw.hints,done:S.hw.done})')
        ok(hw['done'] and hw['e'] == 2, f'wiring done with 2 errors {hw}')
        await pg.screenshot(path=OUT + '05-hw-done.png')
        await pg.click('.modal .actions .btn.go'); await pg.wait_for_timeout(300)
        # ---- code ----
        ok(await pg.is_visible('#labSlider'), 'reading lab is shown next to the blanks')
        await pg.fill('#labSlider', '100'); await pg.wait_for_timeout(600)
        v = int(await pg.inner_text('#labVal')); ok(v > 950, f'lab: covered reading {v}')
        await pg.screenshot(path=OUT + '06-lab.png')
        for k, v in {'b1': '300', 'b2': '9600', 'b3': 'digitalRead', 'b4': 'a0', 'b5': 'Println', 'b6': '<', 'b7': 'HIGH', 'b8': 'LOW'}.items():
            await pg.fill('#blank-' + k, v)
        await pg.click('[data-menu="tools"]'); await pg.hover('.menu .mi:has-text("Board")'); await pg.hover('.menu .mi:has-text("Arduino AVR Boards")')
        await pg.click('.menu .mi span:text-is("Arduino Uno")'); await pg.wait_for_timeout(100)
        await pg.click('#btnVerify'); await pg.wait_for_timeout(1700)
        out = await pg.inner_text('#ideOut'); print(out[:600])
        ok("'a0' was not declared" in out and "suggested alternative: 'A0'" in out, "compile: 'a0' undeclared with suggestion")
        ok("has no member named 'Println'; did you mean 'println'?" in out, 'compile: Serial has no member Println')
        ok('Night_Light.ino:14:21:' in out, 'compile: column of the 2nd blank on line 14 is right')
        await pg.click('#btnCheck'); await pg.wait_for_timeout(200)
        lst = (await pg.inner_text('#codePanel .blist')).replace('\n', ' | ')
        ok('門檻值太低' in lst and '類比' in lst and '相反' in lst, 'feedback: low threshold, digitalRead, < direction')
        await pg.screenshot(path=OUT + '07-code-err.png')
        for k, v in {'b1': '720', 'b3': 'analogRead', 'b4': 'A0', 'b5': 'println', 'b6': '>'}.items(): await pg.fill('#blank-' + k, v)
        await pg.click('#btnCheck'); await pg.wait_for_timeout(200); await pg.click('.modal .actions .btn.go')
        ok(await pg.evaluate('()=>S.code.done'), 'all blanks correct (threshold 720 accepted)')
        # Serial Monitor before upload
        await pg.click('#btnMonitor'); await pg.wait_for_timeout(200)
        ok('上傳' in await pg.inner_text('#codeExplain'), 'Serial Monitor before upload explains it needs an upload')
        await pg.click('#btnUpload'); await pg.wait_for_timeout(1900)
        ok('連接埠' in await pg.inner_text('#codeExplain'), 'upload without port fails')
        await pg.click('#btnUsb'); await pg.click('[data-menu="tools"]'); await pg.hover('.menu .mi:has-text("Port")'); await pg.click('.menu .mi:has-text("(Arduino Uno)")')
        await pg.click('#btnUpload'); await pg.wait_for_timeout(4300)
        ok(await pg.is_visible('.smon-out'), 'result shows the serial monitor')
        await pg.wait_for_timeout(800)
        mon = await pg.inner_text('.smon-out')
        ok('⸮' in mon and '9600' in await pg.inner_text('.smon-note'), 'monitor at 115200 shows garbage and explains baud')
        await pg.screenshot(path=OUT + '08-garbage.png')
        await pg.select_option('.smon-baud', '9600'); await pg.wait_for_timeout(900)
        mon = await pg.inner_text('.smon-out')
        ok(mon.strip().split('\n')[-1].isdigit() and await pg.evaluate('()=>S.up.monitorOk'), f'monitor at 9600 shows readings ({mon.strip().splitlines()[-1]})')
        lit = lambda: pg.evaluate("()=>+document.querySelector('.modal [data-led=\"yellow\"] .ledglow').getAttribute('opacity')")
        ok(await lit() == 0, 'classroom light: LED off')
        await pg.click('.modal [data-dk="100"]'); await pg.wait_for_timeout(500)
        ok(await lit() == 1, 'covered: LED on')
        ok('開燈' in await pg.inner_text('.np-state'), 'state text says on')
        await pg.screenshot(path=OUT + '09-result-dark.png')
        await pg.click('.modal .actions .btn.go'); await pg.wait_for_timeout(400)
        # real page
        ok('int threshold = 720;' in await pg.input_value('#codeText'), "full program uses the student's threshold")
        await pg.fill('[data-rd="room"]', '612'); await pg.fill('[data-rd="dark"]', '1004'); await pg.wait_for_timeout(100)
        ok('808' in await pg.inner_text('#rdAdvice'), 'reading advice suggests the midpoint')
        await pg.fill('[data-rd="dark"]', '1020'); await pg.fill('[data-rd="room"]', '1015'); await pg.wait_for_timeout(100)
        ok('接反' in await pg.inner_text('#rdAdvice'), 'stuck-at-1023 readings point to a reversed sensor')
        await pg.fill('[data-rd="room"]', '612'); await pg.fill('[data-rd="dark"]', '1004'); await pg.fill('[data-rd="torch"]', '35')
        await pg.screenshot(path=OUT + '10-real.png', full_page=True)
        await pg.click('#toReport'); await pg.click('.modal .actions .btn.go'); await pg.wait_for_timeout(500)
        rec = await pg.evaluate('()=>buildRecord()')
        print('score', rec['score'])
        ok(rec['score']['hw'] == 32 and rec['score']['code'] < 40 and rec['score']['up'] == 17, f"scores {rec['score']}")
        ok(rec['code']['blanks'][0]['ans'] == '720' and rec['real']['readings']['dark'] == 1004, 'record keeps threshold and readings')
        await pg.screenshot(path=OUT + '11-report.png', full_page=True)
        async with pg.expect_download() as dl: await pg.click('#dlReport')
        d = await dl.value; path = OUT + 'report.html'; await d.save_as(path)
        ok(d.suggested_filename.startswith('自動夜燈_2C_5'), 'file ' + d.suggested_filename)
        rp = await ctx.new_page(); await rp.goto('file://' + path); await rp.wait_for_timeout(300)
        rt = await rp.inner_text('#r')
        ok('驗證碼有效' in rt and '1004' in rt and '9600 baud' in rt, 'report file valid, shows readings and baud')
        txt = open(path, encoding='utf-8').read().replace('\\"total\\":', '\\"total\\":1', 1)
        open(OUT + 'tampered.html', 'w', encoding='utf-8').write(txt)
        await rp.goto('file://' + OUT + 'tampered.html'); await rp.wait_for_timeout(300)
        ok('驗證失敗' in await rp.inner_text('.rver'), 'tampered report fails')
        await pg.click('#teacherBtn'); await pg.fill('#pwIn', 'dt2026'); await pg.click('.modal .btn.primary'); await pg.wait_for_timeout(200)
        await pg.click('#tpVerify'); await pg.set_input_files('#vFile', [path, OUT + 'tampered.html', os.path.abspath(os.path.dirname(__file__) + '/../lesson3/index.html')]); await pg.wait_for_timeout(400)
        vt = await pg.inner_text('#vTbl'); print(vt)
        ok('有效' in vt and '無效' in vt and ('不是自動夜燈成績報告' in vt or '檔案損壞' in vt), 'verifier rejects tampered and non-report files')
        async with pg.expect_download() as dl2: await pg.click('#vCsv')
        d2 = await dl2.value; await d2.save_as(OUT + 'out.csv'); csv = open(OUT + 'out.csv', encoding='utf-8-sig').read(); print(csv)
        ok('讀數:遮住' in csv and ',1004,' in csv, 'CSV has readings')
        errs = [e for e in errs if 'ERR_TUNNEL' not in e]
        ok(not errs, f'no page errors {errs}')
        await b.close()
    print('FAILURES:', FAIL)
    sys.exit(1 if FAIL else 0)
asyncio.run(main())
